# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Xcent - Jekyll"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Xcent is a Responsive One Page Personal Template for creative people. Xcent can be used for many purposes starting from minimal portfolios, freelancers, photography and much more."


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://beingeorge.com"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "ELLEN DOE"
author_url:  "http://beingeorge.com"
author_image: /images/authorimage.png

# Sidebar Add banner
banner_url: "http://beingeorge.com"
banner_image: images/banner.jpg

# Social links in the site footer
twitter_username: "username"
facebook_username: "username"
googleplus_username: "+username"
github_username: "username"
codepen_username: "username"
dribbble_uername: "username"
medium_username: "@username"
instagram_username: "username"
pinterest_username: "username"
linkedin_username: "username"
weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]
